# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [1]:
import numpy as np

In [ ]:
# ejercicio 1 - Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.

a = np.array([1, 2, 3, 4])

def find_zeros(arr):
    return np.where(arr == 0)[0].size > 0

print(f'{"Sí" if find_zeros(a) else "No"} hay algún cero en el array "a"')

No hay algún cero en el array "a"


In [55]:
# ejercicio 2 - Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.

a = np.array([0, 0, 2, 0])

def find_nonzeros(arr):
    return np.nonzero(arr)[0].size > 0

print(f'{"Sí" if find_nonzeros(a) else "No"} hay algún elemento que no sea cero en el array "a"')

Sí hay algún elemento que no sea cero en el array "a"


In [76]:
# 3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos
# o valores no numéricos (NaN).

a = np.array([1, 2, np.nan, np.inf])

def find_nan(arr):
    return np.any(np.isnan(arr))

def find_inf(arr):
    return np.any(np.isinf(arr))

print(f'{"Sí" if find_nan(a) or find_inf(a) else "No"} hay algún elemento NaN o infinito en el array "a"')

Sí hay algún elemento NaN o infinito en el array "a"


In [72]:
# 4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
a = np.array([1, 2, np.inf])

def find_inf(arr):
    return np.any(np.isinf(arr))
print(f'{"Sí" if find_inf(a) else "No"} hay algún elemento infinito en el array "a"')

Sí hay algún elemento infinito en el array "a"


In [73]:
# 5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN. 
a = np.array([1, np.nan, 3])

def find_nan(arr):
    return np.any(np.isnan(arr))
print(f'{"Sí" if find_nan(a) else "No"} hay algún elemento NaN en el array "a"')

Sí hay algún elemento NaN en el array "a"


In [ ]:
# 6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento
# a elemento contemplando mayor, mayor o igual, menor y menor o igual.

a = np.array([1, 3, 5])
b = np.array([2, 3, 4])

condiciones = [a > b, a < b, a == b]
resultados = [" mayor que ", " menor que ", " igual a "]
comparaciones = np.select(condiciones, resultados, default="")

print(a.astype(str)+comparaciones+b.astype(str))

['1 menor que 2' '3 igual a 3' '5 mayor que 4']


In [97]:
# 7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
arr = np.array([1, 7, 13, 105])
print(f'El arreglo {arr} ocupa {arr.nbytes} bytes de memoria.')

El arreglo [  1   7  13 105] ocupa 32 bytes de memoria.


In [99]:
# 8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
arr_ceros = np.zeros(10)    
arr_ones = np.ones(10)
arr_cincos = np.full(10, 5)
print(arr_ceros, arr_ones, arr_cincos)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [5 5 5 5 5 5 5 5 5 5]


In [ ]:
# 9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
arr_30_70 = np.arange(30, 71)
print(arr_30_70)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [103]:
# 10. Crea un arreglo que contenga los números pares entre 30 y 70.
arr_pares = np.array(range(30, 71, 2))
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
# 11. Crea una matriz identidad de 3x3.
identity_matrix3 = np.eye(3)
print(identity_matrix3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [109]:
# 12. Genera un número aleatorio entre 0 y 1.
np.random.rand()

0.7813300205706736

In [121]:
# 13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
np.random.standard_normal(15)

array([ 0.5578107 , -1.15730238, -0.79174405, -0.76461551, -1.25722236,
       -1.08115836,  0.03092772, -0.35120775,  0.480991  , -1.27001037,
        0.98603728,  1.62418093,  0.41909356, -0.03030451,  2.19419243])

In [122]:
# 14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.

arr_15_55 = np.arange(15, 56)
print(arr_15_55[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [124]:
# 15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
vector = np.linspace(5, 50, 10)
vector

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [ ]:
# 16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
vector = np.arange(0, 21)
vector[9:16] = vector[9:16]*(-1)
vector

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [ ]:
# 17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
a = np.array([1, 2, 3])
lista_a = a.tolist()
print(lista_a)

[1, 2, 3]


In [129]:
# 18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
l = [1, 2, 3]
arr_l = np.array(l)
print(arr_l)

[1 2 3]


In [146]:
# m = np.array([[1, 2], [3, 4]])

m = np.array([[1, 2], [3, 4]])

mask = m % 2 != 0
m[mask] = 0
print(m)

[[0 2]
 [0 4]]


In [142]:
# 19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.

m = np.array([[1, 2], [3, 4]])

n = m[m % 2 == 0]
n

array([2, 4])

In [141]:
# 20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

m = np.array([[1, 2, 3], [4, 5, 6]])

n_filas, n_columnas = m.shape
print(f'Filas:{n_filas}\nColumnas:{n_columnas}')

Filas:2
Columnas:3
